-- VRCycle/Topology/Product.lean
-- VR-Topology v1.0.0 — Stage 4: Product of formal topologies (narrow scope).
--
-- Defines binary product `T₁.prod T₂` of formal topologies via rectangular
-- basic covers (Sambin-style).  Operational product instance provides
-- product operationality (component-wise conjunction).  Non-operational
-- projections `proj₁`, `proj₂` are defined.
--
-- **Narrow scope (per T7/T8/T9 findings cluster)**:
--
-- * Section 6 (`ContinuousMap.pair`) **deferred**.  Pair's `preserves_cov`
--   for `CoverGen` ref_mono case requires relator monotonicity in target
--   argument, which is not present in Stage 3 axioms (Finding T9).
-- * Operational projections **deferred**.  Projections decompose product
--   operationality (conjunction); neither backward (Stage 3 current) nor
--   forward (Finding T8 proposal) `rel_op` direction supports this cleanly.
-- * Operational `pair` **deferred** (Finding T7/T8 territory).  Requires
--   additional `commonRefinement` describability structure not yet known.
-- * Section 7 (declarative universal-property theorems) **deferred** —
--   relies on `pair`.
--
-- Deferred work returns when Stage 6 Tychonoff use case reveals concrete
-- requirements.  This is recognition discipline: abstractions only when
-- concrete use cases justify them.

import VRCycle.Topology.Continuous

namespace VRCycle.Topology

universe u

-- ============================================================
-- Section 1: Product base + preorder
-- ============================================================

namespace FormalTopology

/-- The product type of the underlying carriers. -/
def prodBase (T₁ T₂ : FormalTopology) : Type _ := T₁.S × T₂.S

/-- Component-wise preorder on the product. -/
def prodLe (T₁ T₂ : FormalTopology) : prodBase T₁ T₂ → prodBase T₁ T₂ → Prop :=
  fun p q => T₁.le p.1 q.1 ∧ T₂.le p.2 q.2

theorem prodLe_refl (T₁ T₂ : FormalTopology) :
    ∀ p, prodLe T₁ T₂ p p :=
  fun p => ⟨T₁.le_refl p.1, T₂.le_refl p.2⟩

theorem prodLe_trans (T₁ T₂ : FormalTopology) :
    ∀ p q r, prodLe T₁ T₂ p q → prodLe T₁ T₂ q r → prodLe T₁ T₂ p r :=
  fun _ _ _ ⟨h1, h2⟩ ⟨h3, h4⟩ =>
    ⟨T₁.le_trans _ _ _ h1 h3, T₂.le_trans _ _ _ h2 h4⟩

-- ============================================================
-- Section 2: Rectangular basic covers
-- ============================================================

/-- **Rectangular basic covers**: `U` is a basic cover of `⟨a₁, a₂⟩` when
`U = U₁ × U₂` for some component covers `T₁.cov a₁ U₁` and `T₂.cov a₂ U₂`.
Sambin's standard formulation for product formal topologies. -/
def prodBasicCov (T₁ T₂ : FormalTopology) :
    prodBase T₁ T₂ → Set (prodBase T₁ T₂) → Prop :=
  fun p U =>
    ∃ U₁ U₂, T₁.cov p.1 U₁ ∧ T₂.cov p.2 U₂ ∧
      U = {q | q.1 ∈ U₁ ∧ q.2 ∈ U₂}

-- ============================================================
-- Section 3: Product formal topology
-- ============================================================

/-- **Binary product of formal topologies**, built via `ofPresentation`
from component-wise preorder and rectangular basic covers.  The full
cover relation is generated by `CoverGen` from `prodBasicCov`. -/
def prod (T₁ T₂ : FormalTopology) : FormalTopology :=
  FormalTopology.ofPresentation
    (prodBase T₁ T₂)
    (prodLe T₁ T₂)
    (prodLe_refl T₁ T₂)
    (prodLe_trans T₁ T₂)
    (prodBasicCov T₁ T₂)

end FormalTopology

-- ============================================================
-- Section 4: Operational product instance
-- ============================================================

namespace OperationalFormalTopology

/-- Operational predicate on the product: both components must be operational. -/
def prodIsOperational
    (T₁ T₂ : FormalTopology)
    [OperationalFormalTopology T₁] [OperationalFormalTopology T₂] :
    FormalTopology.prodBase T₁ T₂ → Prop :=
  fun p =>
    OperationalFormalTopology.IsOperational p.1 ∧
    OperationalFormalTopology.IsOperational p.2

/-- **Operational rectangular basic cover** for the product (Finding T14
amendment).  Uses component-level `basicCov` presentations (not full
`T.cov`), so that `CompactWitness.cover_closure` for the product can
apply component `cover_closure` fields directly in Stage 6 Tychonoff.

Contrast with `FormalTopology.prodBasicCov` (uses full `T.cov`): that
one is the basic cover for the underlying `FormalTopology.prod` and is
used by projections.  This one is the basic cover for the operational
presentation of the product, used in `instProd.basicCov`. -/
def opProdBasicCov
    (T₁ T₂ : FormalTopology)
    [inst₁ : OperationalFormalTopology T₁]
    [inst₂ : OperationalFormalTopology T₂] :
    FormalTopology.prodBase T₁ T₂ → Set (FormalTopology.prodBase T₁ T₂) → Prop :=
  fun p U =>
    ∃ U₁ U₂, inst₁.basicCov p.1 U₁ ∧ inst₂.basicCov p.2 U₂ ∧
      U = {q | q.1 ∈ U₁ ∧ q.2 ∈ U₂}

/-- **Operational instance on the product formal topology.**  Operational
elements are pairs whose both components are operational.  Basic cover
is the operational rectangular cover (`opProdBasicCov`, Finding T14). -/
instance instProd
    (T₁ T₂ : FormalTopology)
    [inst₁ : OperationalFormalTopology T₁] [inst₂ : OperationalFormalTopology T₂] :
    OperationalFormalTopology (FormalTopology.prod T₁ T₂) where
  IsOperational := prodIsOperational T₁ T₂
  basicCov := opProdBasicCov T₁ T₂
  op_preserved_by_le hle hop :=
    ⟨inst₁.op_preserved_by_le hle.1 hop.1, inst₂.op_preserved_by_le hle.2 hop.2⟩

end OperationalFormalTopology

-- ============================================================
-- Section 5: Non-operational projections
-- ============================================================

namespace ContinuousMap

/-- **First projection** from the product formal topology to the first
component.  Relator: `rel a p := a = p.1`.  Non-operational only;
operational version deferred (Finding T8 territory). -/
def proj₁ (T₁ T₂ : FormalTopology) :
    ContinuousMap (FormalTopology.prod T₁ T₂) T₁ where
  rel a p := a = p.1
  respects_le := by
    rintro b a a' hrel hle
    refine ⟨a'.1, ?_, rfl⟩
    rw [hrel]
    exact hle.1
  preserves_cov := by
    rintro b a U hrel hCov
    -- hrel : b = a.1, hCov : T₁.cov b U
    have hCov₁ : T₁.cov a.1 U := hrel ▸ hCov
    have hCov₂ : T₂.cov a.2 ({a.2} : Set T₂.S) := T₂.cov_singleton a.2
    -- Build basic rectangular cover U₁=U, U₂={a.2}
    have hBasic : (FormalTopology.prod T₁ T₂).cov a
        {q : FormalTopology.prodBase T₁ T₂ | q.1 ∈ U ∧ q.2 ∈ ({a.2} : Set T₂.S)} :=
      CoverGen.basic ⟨U, {a.2}, hCov₁, hCov₂, rfl⟩
    -- Enlarge via cov_mono
    refine (FormalTopology.prod T₁ T₂).cov_mono a _ _ ?_ hBasic
    rintro q ⟨h₁, _⟩
    exact ⟨q.1, h₁, rfl⟩

/-- **Second projection** from the product formal topology to the second
component.  Relator: `rel a p := a = p.2`.  Non-operational only;
operational version deferred. -/
def proj₂ (T₁ T₂ : FormalTopology) :
    ContinuousMap (FormalTopology.prod T₁ T₂) T₂ where
  rel a p := a = p.2
  respects_le := by
    rintro b a a' hrel hle
    refine ⟨a'.2, ?_, rfl⟩
    rw [hrel]
    exact hle.2
  preserves_cov := by
    rintro b a U hrel hCov
    have hCov₂ : T₂.cov a.2 U := hrel ▸ hCov
    have hCov₁ : T₁.cov a.1 ({a.1} : Set T₁.S) := T₁.cov_singleton a.1
    have hBasic : (FormalTopology.prod T₁ T₂).cov a
        {q : FormalTopology.prodBase T₁ T₂ | q.1 ∈ ({a.1} : Set T₁.S) ∧ q.2 ∈ U} :=
      CoverGen.basic ⟨{a.1}, U, hCov₁, hCov₂, rfl⟩
    refine (FormalTopology.prod T₁ T₂).cov_mono a _ _ ?_ hBasic
    rintro q ⟨_, h₂⟩
    exact ⟨q.2, h₂, rfl⟩

end ContinuousMap

-- ============================================================
-- Section 8: Smoke tests
-- ============================================================

namespace Examples

/-- The product `Bool × Bool` formal topology exists. -/
example : FormalTopology :=
  FormalTopology.prod Bool.formalTopology Bool.formalTopology

/-- The product `Bool × Bool` carries an operational structure via the
operational instance. -/
example : OperationalFormalTopology
    (FormalTopology.prod Bool.formalTopology Bool.formalTopology) :=
  inferInstance

/-- First projection from `Bool × Bool` to `Bool`. -/
example : ContinuousMap
    (FormalTopology.prod Bool.formalTopology Bool.formalTopology)
    Bool.formalTopology :=
  ContinuousMap.proj₁ _ _

/-- Second projection from `Bool × Bool` to `Bool`. -/
example : ContinuousMap
    (FormalTopology.prod Bool.formalTopology Bool.formalTopology)
    Bool.formalTopology :=
  ContinuousMap.proj₂ _ _

end Examples

end VRCycle.Topology
