-- VRCycle: Algebra.lean
-- Module index for the VR Operational Algebra cycle — v1.0.0 (stable release).
--
-- ## What this module is
--
-- The eighth work in the VR Cycle: **Operational Algebra**.
--
-- **v1.0.0 — Stable release**. Mathematical scope closed at v0.4.0.
-- v1.0.0 is a documentation-polish release: file headers, findings catalog,
-- cross-references, and README brought to publication-quality form.
-- No new Lean content in v1.0.0; v1.0.0 ≅ v0.4.0 mathematically.
--
-- Demonstrates that the VR-Apparatus framework (meta-formalised in v1.0.0,
-- DOI 10.5281/zenodo.20380344) extends naturally to algebraic structures.
-- Specifically: the predicate-wrapping apparatus (PredicateOperationality)
-- applies to additive groups, rings, multiplicative groups, fields, and modules,
-- with subgroups and substantive Mode B audit completing the algebraic hierarchy.
--
-- ## Architecture
--
-- ### v0.1.0 (additive groups — complete, tag v1.8-vr-operational-algebra-v0.1.0)
-- VRCycle/Algebra/AddGroup.lean     — OperationalAddGroup typeclass (v0.1.0 Stage 1)
-- VRCycle/Algebra/Instances.lean    — ℤ and ZMod n instances (v0.1.0 Stages 2, 4)
-- VRCycle/Algebra/ModeA.lean        — Mode A closure theorems + PredicateOperationality (v0.1.0 Stage 3)
-- VRCycle/Algebra/Subgroups.lean    — Operational subgroups (v0.1.0 Stage 5)
-- VRCycle/Algebra/ModeBExample.lean — Mode B skeleton → substantive audit (v0.1.0→v0.2.0)
--
-- ### v0.2.0 (rings — complete, tag v1.9-vr-operational-algebra-v0.2.0)
-- VRCycle/Algebra/Ring.lean         — OperationalRing typeclass + bridge instance (v0.2.0 Stages 1-2)
-- VRCycle/Algebra/Instances.lean    — ℤ and ZMod n as OperationalRing (v0.2.0 Stages 3-4)
-- VRCycle/Algebra/ModeA.lean        — mul_isModeAOp, npow_isOperational (v0.2.0 Stage 5)
-- VRCycle/Algebra/ModeBExample.lean — Substantive Mode B audit, sorryAx eliminated (v0.2.0 Stage 6)
--
-- ### v0.3.0 (fields + multiplicative groups — Stages 1-5 complete)
-- VRCycle/Algebra/MulGroup.lean     — OperationalGroup typeclass, multiplicative (v0.3.0 Stage 1)
-- VRCycle/Algebra/Field.lean        — OperationalField typeclass + bridges (v0.3.0 Stages 2, 5)
-- VRCycle/Algebra/Instances.lean    — ℚ as OperationalField + ℚˣ demos (v0.3.0 Stages 3, 5)
-- VRCycle/Algebra/ModeA.lean        — Mode A theorems for multiplicative groups + field (v0.3.0 Stage 4)
--
-- ### v0.4.0 (zsmul + A15 investigation + modules — Stages 1-5 complete)
-- VRCycle/Algebra/ModeA.lean        — zsmul_isOperational (v0.4.0 Stage 1)
-- VRCycle/Algebra/Module.lean       — OperationalModule typeclass, bridge-based (v0.4.0 Stage 3)
--   Stage 1: zsmul_isOperational closes v0.3.0 Stage 4 gap (additive ℤ-scalar).
--   Stage 2: A15 import-context investigated; Outcome C (structural Classical.choice confirmed).
--   Stage 3: OperationalModule typeclass defined (bridge: OperationalRing R + OperationalAddGroup M).
--   Stage 4: ℤ and ℚ as OperationalModule instances (Instances.lean §12).
--   Stage 5: smul_isModeAOp Mode A theorem (ModeA.lean §11; fourth Finding A3 confirmation).
--
-- ## Stage index (v0.1.0)
--
-- Stage 1 (complete): OperationalAddGroup typeclass. Finding A0: multiplicative
--   typeclass removed — no v0.1.0 multiplicative instances (recognition discipline).
-- Stage 2: ℤ instance (Instances.lean, OperationalAddGroup ℤ).
-- Stage 3: Mode A theorems + PredicateOperationality instance (ModeA.lean).
-- Stage 4: ZMod n instance (Instances.lean extension).
-- Stage 5: Operational subgroups (Subgroups.lean).
-- Stage 6: Mode B skeleton example (ModeBExample.lean). Findings A7, A8.
-- Stage 7: Polish, full audit, git. Tag v1.8-vr-operational-algebra-v0.1.0.
--
-- ## Stage index (v0.2.0)
--
-- Stage 1 (complete): OperationalRing typeclass (Ring.lean).
--   extends Ring R with IsOperational + 5 closure axioms (0, +, -, 1, *).
--   Axiom profile: [].
-- Stage 2 (complete): OperationalCommRing OMITTED (Finding A9 — recognition discipline).
--   Bridge instance OperationalRing.toOperationalAddGroup implemented.
--   Axiom profile of bridge: [].
-- Stage 3 (complete): ℤ as OperationalRing (Instances.lean §5-6).
--   instOperationalRingInt; IsOperational := fun _ => True.
--   Finding A10 first observed: ring ceiling = additive-group ceiling = [propext].
-- Stage 4 (complete): ZMod n as OperationalRing (Instances.lean §7-8).
--   instOperationalRingZMod [NeZero n]; IsOperational := fun _ => True.
--   Finding A10 confirmed: ring ceiling = [propext, Quot.sound] (unchanged from additive).
-- Stage 5 (complete): Ring Mode A theorems (ModeA.lean §4-7).
--   instPredOpRing, mul_isModeAOp, npow_isOperational.
--   Recognition discipline: one_isOperational_bridge omitted (is already a typeclass field);
--   mul_chain_isOperational omitted (derivable from compose).
--   Axiom profile: all [].
-- Stage 6 (complete): Substantive Mode B audit (ModeBExample.lean §2).
--   image_isOperationalAddSubgroup_isModeBOp: sorry eliminated.
--   Key step: obtain ⟨x, hxS, rfl⟩ := hy; exact hW x (hS x hxS).
--   Finding A11: algebraic Mode B = one proof step; contrast analytic Mode B (limits, choice).
--   Axiom profile of main theorem: [propext] (down from [propext, sorryAx]).
-- Stage 7 (complete): Polish, full audit, README, git.
--   Tag: v1.9-vr-operational-algebra-v0.2.0.
--
-- ## Public object inventory (complete)
--
-- ### v0.1.0 (31 objects across 5 files)
--
-- AddGroup.lean (1):
--   OperationalAddGroup (class)
--
-- Instances.lean §1-4 (8):
--   instOperationalAddGroupInt        (instance, OperationalAddGroup ℤ)
--   int_isOperational                 (theorem, ∀ n : ℤ, IsOperational n)
--   int_add_isOperational             (theorem, closure under +)
--   int_three_plus_five_isOperational (theorem, concrete demo)
--   instOperationalAddGroupZMod       (instance, OperationalAddGroup (ZMod n))
--   zmod_isOperational                (theorem, ∀ x : ZMod n, IsOperational x)
--   zmod5_add_isOperational           (theorem, concrete closure)
--   zmod5_two_plus_three_isOperational (theorem, concrete demo)
--
-- ModeA.lean §1-3 (5):
--   instPredOpAddGroup    (instance, PredicateOperationality G IsOperational)
--   add_isModeAOp         (theorem, IsModeAOp₂ (+))
--   neg_isModeAOp         (theorem, IsModeAOp (-))
--   sub_isModeAOp         (theorem, IsModeAOp₂ (-))
--   nsmul_isOperational   (theorem, ∀ n : ℕ, IsOperational (n • a))
--
-- Subgroups.lean (8):
--   IsOperationalAddSubgroup                 (def, ∀ x ∈ H, IsOperational x)
--   bot_isOperationalAddSubgroup             (theorem, ⊥ is always operational)
--   top_isOperationalAddSubgroup             (theorem, ⊤ is operational if all-operational)
--   inf_isOperationalAddSubgroup             (theorem, one-sided: H operational → H ⊓ K operational)
--   inf_isOperationalAddSubgroup_bilateral   (theorem, bilateral intersection corollary)
--   int_bot_isOperationalAddSubgroup         (theorem, ℤ: ⊥ is operational)
--   int_top_isOperationalAddSubgroup         (theorem, ℤ: ⊤ is operational)
--   int_inf_top_isOperationalAddSubgroup     (theorem, ℤ: ⊤ ⊓ K is operational)
--
-- Note: Finding A6 — OperationalSubgroup as bundled structure was omitted (predicate suffices).
-- The three instances (instInfOperationalSubgroup, instTopOperationalSubgroup,
-- instBotOperationalSubgroup) listed in earlier drafts were never implemented.
-- The predicate-based design (IsOperationalAddSubgroup) is the final form.
--
-- ModeBExample.lean (9):
--   neg_isModeBOp                              (theorem, Mode B for negation)
--   neg_modeb_lift                             (def, Mode B lift)
--   neg_modeb_lift_val                         (theorem, @[simp])
--   image_isOperationalAddSubgroup_isModeBOp   (theorem, substantive Mode B audit)
--   operationalImage_lift                      (def, Mode B lift)
--   operationalImage_lift_val                  (theorem, @[simp])
--   int_ker_isOperationalAddSubgroup           (theorem, concrete ℤ kernel)
--   int_image_isOperationalAddSubgroup         (theorem, concrete ℤ image)
--   int_to_zmod_ker_isOperationalAddSubgroup   (theorem, concrete ℤ→ZMod kernel)
--
-- ### v0.3.0 (Stages 1-5 complete; 17 named objects across 4 files)
--
-- MulGroup.lean (1):
--   OperationalGroup                       (class, extends Group G)
--
-- Field.lean (3):
--   OperationalField                           (class, extends Field K)
--   OperationalField.toOperationalRing         (instance, bridge OperationalField → OperationalRing)
--   OperationalField.toOperationalGroupUnits   (instance, bridge OperationalField → OperationalGroup Kˣ)
--
-- Instances.lean §9-10 (5):
--   instOperationalFieldRat                (instance, OperationalField ℚ)
--   rat_half_isOperational                 (theorem, IsOperational (1/2 : ℚ))
--   rat_half_plus_third_isOperational      (theorem, closure + demo)
--   rat_product_inv_isOperational          (theorem, closure * and ⁻¹ demo)
--   rat_sub_isOperational                  (theorem, closure - demo)
--
-- ModeA.lean §8-10 (8):
--   MulGroup.instPredOpMulGroup            (instance, PredicateOperationality G IsOperational)
--   MulGroup.mul_isModeAOp                 (theorem, IsModeAOp₂ (*))
--   MulGroup.inv_isModeAOp                 (theorem, IsModeAOp (·⁻¹) for OperationalGroup)
--   MulGroup.div_isModeAOp                 (theorem, IsModeAOp₂ (/))
--   MulGroup.npow_isOperational            (theorem, ∀ n : ℕ, IsOperational (a ^ n))
--   MulGroup.zpow_isOperational            (theorem, ∀ n : ℤ, IsOperational (a ^ n))
--   instPredOpField                        (instance, PredicateOperationality K IsOperational)
--   inv_isModeAOp_field                    (theorem, IsModeAOp (·⁻¹) for OperationalField)
--   [7 examples in §§8-10, not public objects]
--
-- Instances.lean §11 (5 examples, not public objects):
--   [OperationalGroup ℚˣ via bridge]       (example, bridge fires for ℚˣ)
--   [1 : ℚˣ is operational]               (example, unit element)
--   [2ˣ ∈ ℚˣ is operational]              (example, concrete unit via mk0)
--   [2ˣ * 3ˣ is operational]              (example, mul closure in ℚˣ)
--   [(2ˣ)⁻¹ is operational]               (example, inv closure in ℚˣ)
--
-- (ℚˣ examples are anonymous examples, not named public objects;
--  the key deliverable is OperationalField.toOperationalGroupUnits in Field.lean)
--
-- ### v0.4.0 (Stages 1-5 complete; 9 new objects)
--
-- ModeA.lean §2 (1):
--   zsmul_isOperational   (theorem, ∀ n : ℤ, IsOperational (n • a))
--   [Stage 1: closes v0.3.0 Stage 4 gap; additive ℤ-scalar analogue of zpow_isOperational]
-- Stage 2: A15 reconnaissance (Outcome C — see Finding A16).
--   No new public objects. Finding A16 documented in findings catalog below.
-- Module.lean (1):
--   OperationalModule                      (class, bridge: [OperationalRing R] + [OperationalAddGroup M])
--   [Stage 3: bridge-based; single new axiom smul_isOperational; no new predicate on M]
-- Instances.lean §12 (6):
--   instOperationalModuleIntInt            (instance, OperationalModule ℤ ℤ)
--   int_smul_isOperational                 (theorem, general ℤ scalar closure)
--   int_two_smul_three_isOperational       (theorem, concrete ℤ demo)
--   instOperationalModuleRatRat            (instance, OperationalModule ℚ ℚ)
--   rat_smul_isOperational                 (theorem, general ℚ scalar closure)
--   rat_half_smul_third_isOperational      (theorem, concrete ℚ demo)
--   [Stage 4: diamond auto-resolved for ℤ; ℚ via bridge chain; ceiling unchanged]
-- ModeA.lean §11 (1):
--   smul_isModeAOp                         (theorem, IsModeAOp (r • ·) for OperationalModule R M)
--   [Stage 5: heterogeneous binary op → IsModeAOp (unary) on M for fixed r;
--    fourth Finding A3 confirmation; instPredOpAddGroup reused without modification]
--
-- ### v0.2.0 (15 new objects across 3 files; 1 sorry eliminated in ModeBExample.lean)
--
-- Ring.lean (2):
--   OperationalRing                        (class, extends Ring R)
--   OperationalRing.toOperationalAddGroup  (instance, bridge)
--
-- Instances.lean §5-8 (10):
--   instOperationalRingInt              (instance, OperationalRing ℤ)
--   int_one_isOperational               (theorem, IsOperational 1 in ℤ)
--   int_mul_isOperational               (theorem, closure under * in ℤ)
--   int_two_mul_three_isOperational     (theorem, concrete demo)
--   int_sum_mul_isOperational           (theorem, chained + and *)
--   instOperationalRingZMod             (instance, OperationalRing (ZMod n))
--   zmod5_one_isOperational             (theorem, IsOperational 1 in ZMod 5)
--   zmod5_mul_isOperational             (theorem, closure under * in ZMod 5)
--   zmod5_two_mul_three_isOperational   (theorem, concrete demo)
--   zmod7_sum_mul_isOperational         (theorem, chained + and * in ZMod 7)
--
-- ModeA.lean §4-7 (3):
--   instPredOpRing      (instance, PredicateOperationality R IsOperational)
--   mul_isModeAOp       (theorem, IsModeAOp₂ (*))
--   npow_isOperational  (theorem, ∀ n : ℕ, IsOperational (a ^ n))
--
-- ## Findings catalog (v0.1.0 + v0.2.0 + v0.3.0 Stages 1-4)
--
-- ### v0.1.0 Findings (A0–A8)
--
-- A0: Multiplicative typeclass OMITTED — no v0.1.0 instances exist.
--     Recognition discipline: do not abstract preemptively.
--     (Parallel: OperationalCommRing omitted in v0.2.0, Finding A9.)
--
-- A1: Lean 4 `extends` for typeclasses works correctly with mathlib's Ring hierarchy.
--     (First confirmed in v0.1.0 with AddGroup; extended to Ring in v0.2.0.)
--
-- A2: `toAddGroup := inferInstance` resolves the bridge correctly.
--     Lean synthesises the AddGroup instance from AddCommGroup via the ring chain.
--
-- A3: VR-Apparatus framework reuses WITHOUT modification for additive groups.
--     `PredicateOperationality` zero-field marker requires no ring-specific changes.
--     Confirmed in v0.2.0: apparatus reuse extends to full ring structure (instPredOpRing).
--
-- A4: neg_isModeAOp pulls [propext] despite neg being defined algebraically.
--     Lean's Neg elaboration requires propositional extensionality for lambda reductions.
--     Multiplication does NOT pull [propext] (pure algebraic composition).
--     Contrast: mul_isModeAOp is [] in v0.2.0, confirming [] is possible for binary ops.
--
-- A5: Axiom ceiling hierarchy for algebraic structures:
--     [] → [propext] → [propext, Quot.sound] → [propext, Classical.choice, Quot.sound].
--     ℤ objects: [propext]. ZMod n objects: [propext, Quot.sound].
--     Classical.choice ABSENT from all algebraic objects (confirmed v0.1.0 + v0.2.0).
--
-- A6: IsOperationalAddSubgroup as predicate (not typeclass) is the correct design.
--     No inheritance diamond; no elaboration issues. ⊥/⊤/⊓ proved as simple theorems.
--     Omitted: OperationalSubgroup as typeclass (redundant; predicate suffices for v0.1.0).
--
-- A7: Mode B operation on algebraic objects is structurally similar to Mode B on
--     analytic objects (VR-Audit Hahn-Banach), but the algebraic case is simpler:
--     the witness is immediate (subgroup membership), not a choice function.
--
-- A8: Trivial vs substantive Mode B:
--     neg_isModeBOp (trivial): W = True, proof = trivial.
--     image_isOperationalAddSubgroup_isModeBOp (substantive): W = operational-morphism
--     condition, proof extracts constructive witness from mem_map.
--
-- ### v0.2.0 Findings (A9–A11)
--
-- A9: OperationalCommRing OMITTED — recognition discipline applied proactively.
--     Form A (extends CommRing R, OperationalRing R): FAILS — immediate diamond on toRing.
--     Form B (extends CommRing R, all axioms duplicated): COMPILES but no new content.
--     Verdict: [OperationalRing R] [CommRing R] in context suffices; no new typeclass.
--     Direct analogue of Finding A0 for the multiplicative commutative case.
--
-- A10: Ring extension does NOT escalate the axiom ceiling.
--     ℤ: OperationalAddGroup ceiling = OperationalRing ceiling = [propext].
--     ZMod n: OperationalAddGroup ceiling = OperationalRing ceiling = [propext, Quot.sound].
--     Classical.choice ABSENT from all ring objects (including mul, pow, one).
--     Principle: ceiling determined by underlying type's infrastructure, not algebraic depth.
--
-- A11: Algebraic Mode B audit requires ONE PROOF STEP.
--     image_isOperationalAddSubgroup_isModeBOp proof:
--       obtain ⟨x, hxS, rfl⟩ := hy; exact hW x (hS x hxS)
--     Reason: AddSubgroup.mem_map provides CONSTRUCTIVE existential (no Classical.choice).
--     Contrast with analytic Mode B (Hahn-Banach): limit arguments, classical extension,
--     substantial infrastructure. Algebraic Mode B is mechanically extractable from
--     constructive witnesses built into mathlib's algebraic API.
--
-- ### v0.3.0 Findings (A12–A15, Stages 1-4)
--
-- A12: Recognition discipline REVERSAL — OperationalGroup introduced when justified.
--     v0.1.0 Finding A0: multiplicative OperationalGroup omitted (no instances).
--     v0.3.0 Stage 1: multiplicative OperationalGroup INTRODUCED (Fields → Kˣ).
--     v0.3.0 Stage 5: bridge instance OperationalField.toOperationalGroupUnits delivered.
--     The abstraction was revived in Stage 1 because THIS bridge exists; Stage 5 proves it.
--     Bidirectional recognition discipline: remove preemptive abstractions AND
--     introduce justified abstractions when users (instances) arrive.
--     Full circle from A0 (removed) → A12 (anticipated) → Stage 5 (concrete).
--     ℚˣ as OperationalGroup is the natural first instance — Finding A12 CONFIRMED.
--
-- A13: OperationalField currently does not introduce axioms beyond those of Field K.
--     OperationalField class: [propext, Quot.sound] — inherited from Field's RatCast.
--     Bridge OperationalField → OperationalRing: [propext, Quot.sound].
--     This is an empirical observation for the current v0.3.0 build, not a meta-law.
--     The ceiling is determined by Field K's infrastructure (DivisionRing → RatCast),
--     not by the VR operational layer added above it.
--
-- A14: ℚ concrete instances reach full analysis ceiling [propext, Classical.choice, Quot.sound].
--     instOperationalFieldRat and all ℚ demonstration theorems: full ceiling.
--     Root cause: Rat.instField (via commGroupWithZero inverse infrastructure).
--     This is the first time Classical.choice appears in concrete algebraic instances
--     in the VR Cycle (previously absent from all ℤ and ZMod n objects).
--     Principle: ℚ's field structure for inversion requires classical reasoning about
--     the zero case (commGroupWithZero convention: 0⁻¹ = 0 requires choice in the proof).
--
-- A15: Import-context ceiling escalation for inv_isModeAOp_field.
--     inv_isModeAOp_field (generic, [OperationalField K]): [propext, Classical.choice, Quot.sound].
--     instPredOpField (same [OperationalField K], no (·⁻¹) in type): [propext, Quot.sound].
--     Root cause: Apparatus import chain imports Mathlib.Data.Real.Basic (via
--     VRCycle.Apparatus.ModeA → VRCycle.Apparatus.Wrapping → VRCycle.Audit.Computable
--     → Mathlib.Data.Real.Basic). This introduces ℝ instances that affect how Lean
--     resolves Inv K for generic [Field K] when (·⁻¹) appears in the IsModeAOp type.
--     The Classical.choice is an import-context effect, NOT a logical property of
--     inv_isOperational. The logical ceiling remains [propext, Quot.sound].
--     Contrast: MulGroup.inv_isModeAOp (same IsModeAOp + inv structure, [OperationalGroup G]):
--     [propext] — no import escalation because Group doesn't import ℝ-related Mathlib.
--     This finding extends A5: import context can escalate the apparent ceiling
--     beyond what the logic requires.
--
-- ### v0.4.0 Findings (A16–A19, Stages 1-5)
--
-- A16: A15 structural confirmation — Classical.choice is not removable by isolation.
--     Stage 2 reconnaissance (v0.4.0): systematic isolation attempts confirm Outcome C.
--     Two affected objects, two distinct root causes:
--
--     (1) inv_isModeAOp_field [propext, Classical.choice, Quot.sound]:
--         Root: VRCycle.Apparatus.ModeA transitively imports Mathlib.Data.Real.Basic,
--         which introduces instances affecting Inv K elaboration when (·⁻¹) appears
--         in the IsModeAOp type. IsModeAOp cannot be used without the apparatus import;
--         therefore isolation via file separation is impossible.
--         Test: minimal-import file (no Instances.lean) still shows Classical.choice.
--         Confirmed: apparatus chain is the root cause, not ℚ instances.
--
--     (2) OperationalField.toOperationalGroupUnits [propext, Classical.choice, Quot.sound]:
--         Root: proof-structural. The TYPE is clean (sorry-proof gives [propext, Quot.sound]).
--         But any valid proof must use Units.val_inv_eq_inv_val to connect
--         (u⁻¹ : Kˣ).val (= u.inv, definitional) to (u.val)⁻¹ (field inverse).
--         After this rewrite, the goal contains field-level (u : K)⁻¹, which
--         inherits Classical.choice in the elaboration context. No alternative proof
--         path exists: the OperationalField closure axioms don't allow proving
--         IsOperational u.inv from IsOperational u.val without field inverse.
--         Note: Units.val_inv_eq_inv_val itself is [] (axiom-free); Classical.choice
--         enters through the field-level (·⁻¹) expression in the resulting goal.
--
--     Conclusion: A15 is structurally embedded, not incidental. The Classical.choice
--     reflects genuine mathematical structure of field inversion. No refactoring
--     eliminates it without changing the predicate or the apparatus architecture.
--     Programme remains honest: these two objects are the only non-eliminable
--     sources of Classical.choice in the algebraic hierarchy.
--     Extended A5 principle: import context CAN escalate; AND proof-structural
--     requirements CAN require Classical.choice for field inversion specifically.
--
-- A17: Apparatus reuse confirmed for Module — fourth and strongest confirmation of A3.
--     smul_isModeAOp (Stage 5) uses instPredOpAddGroup from ModeA.lean §1 — the same
--     instance introduced in v0.1.0 for OperationalAddGroup. No new PredicateOperationality
--     instance was registered for OperationalModule.
--     Progression across four algebraic structures:
--       v0.1.0: instPredOpAddGroup registered (OperationalAddGroup — new instance required).
--       v0.2.0: instPredOpRing registered (OperationalRing — Ring adds mul, pow, one).
--       v0.3.0: instPredOpField registered (OperationalField — Field adds inv).
--       v0.4.0: NO new instance for OperationalModule — reuses instPredOpAddGroup unchanged.
--     Bridge-based design (no new predicate on M) means apparatus reuse is not merely
--     "extends naturally" but literally "uses the existing v0.1.0 instance unchanged."
--     Root cause: OperationalModule introduces no new predicate on M (Decision A);
--     M's predicate is still OperationalAddGroup.IsOperational; apparatus sees same type.
--     Principle: apparatus generality is maximal for bridge-based structures.
--     Connection to A3: apparatus framework, designed for additive groups, is
--     genuinely structure-agnostic — it operates on predicates, not on algebraic structure.
--
-- A18: zsmul_isOperational closes v0.3.0 Stage 4 gap (v0.4.0 Stage 1).
--     MulGroup.zpow_isOperational (v0.3.0): integer exponentiation for OperationalGroup.
--     Gap noted: additive analogue (zsmul : ℤ → G → G) not proved in v0.1.0.
--     Resolution: zsmul_isOperational (v0.4.0 Stage 1) proved by ℤ case split +
--     nsmul_isOperational (ℕ induction). Proof mirrors zpow_isOperational structure.
--     Axiom profile: [] — purely algebraic, same as zpow_isOperational.
--     Symmetry table complete:
--       nsmul_isOperational (ℕ-scalar, v0.1.0) ↔ MulGroup.npow_isOperational (ℕ-power, v0.3.0)
--       zsmul_isOperational (ℤ-scalar, v0.4.0) ↔ MulGroup.zpow_isOperational (ℤ-power, v0.3.0)
--     Engineering note: zsmul proof requires explicit rw [natCast_zsmul] + rw [negSucc_zsmul]
--     (unlike zpow which admits bare `exact` via definitional unfolding). Documented in
--     ModeA.lean §2 proof note.
--
-- A19: First heterogeneous binary operation in VR Cycle — Mode A form constraint.
--     All prior binary operations in the VR Cycle were homogeneous: (+), (*), (-), (/).
--     Scalar action smul : R → M → M is heterogeneous: input types R and M differ.
--     IsModeAOp₂ f requires f : T → T → T (homogeneous single predicate P on one type T).
--     For heterogeneous smul, the correct Mode A form is IsModeAOp (r • · : M → M)
--     (unary predicate on M) for fixed operational scalar r : R.
--     The operationality of r : R is a HYPOTHESIS (OperationalRing.IsOperational r),
--     not a conclusion produced by IsModeAOp. IsModeAOp covers the M-side:
--       ∀ m : M, OperationalAddGroup.IsOperational m → OperationalAddGroup.IsOperational (r • m).
--     PLAN.md error: initially suggested `IsModeAOp₂ (· • · : R → M → M)` — incorrect
--     because IsModeAOp₂ requires homogeneous type. Sonnet caught and corrected during
--     Stage 5 reconnaissance (Variant A разделение работ functioning as designed).
--     Engineering principle: apparatus architecture (IsModeAOp₂ homogeneous constraint)
--     naturally and correctly distinguishes homogeneous from heterogeneous binary operations.
--     The correction is a methodological confirmation, not a limitation: the apparatus
--     accurately reflects the mathematical distinction between internal and external operations.
--
-- ## Axiom profile summary (v0.1.0 + v0.2.0 + v0.3.0 Stages 1-5; v0.4.0 Stages 1-5)
--
--   []                              — OperationalAddGroup, OperationalRing, OperationalGroup
--                                     (v0.3.0 Stage 1), OperationalModule (v0.4.0 Stage 3),
--                                     all bridge instances, instOperationalModuleIntInt,
--                                     all PredicateOperationality instances except instPredOpField,
--                                     add_/mul_/sub_isModeAOp, nsmul_/npow_isOperational,
--                                     zsmul_isOperational (v0.4.0 Stage 1),
--                                     smul_isModeAOp (v0.4.0 Stage 5),
--                                     MulGroup.mul_/div_isModeAOp, MulGroup.npow_/zpow_isOp,
--                                     IsOperationalAddSubgroup, ⊥/⊤/⊓ theorems,
--                                     neg_isModeBOp, image_isOperationalAddSubgroup_isModeBOp
--
--   [propext]                       — ℤ AddGroup instances + demonstrations,
--                                     ℤ Ring instances + demonstrations,
--                                     ℤ Module instances + demonstrations (v0.4.0 Stage 4),
--                                     neg_isModeAOp (Neg elaboration, Finding A4),
--                                     MulGroup.inv_isModeAOp (Inv elaboration, A4 mirror),
--                                     Mode B lifts and lift_val,
--                                     int_ker/image_isOperationalAddSubgroup
--
--   [propext, Quot.sound]           — ZMod n AddGroup instances + demonstrations,
--                                     ZMod n Ring instances + demonstrations,
--                                     Subgroups.lean theorems involving ZMod n,
--                                     int_to_zmod_ker_isOperationalAddSubgroup,
--                                     OperationalField (v0.3.0 Stage 2),
--                                     OperationalField.toOperationalRing (bridge),
--                                     instPredOpField
--
--   [propext, Classical.choice, Quot.sound]
--                                   — ℚ instances + demonstrations (v0.3.0 Stage 3,
--                                     Finding A14: Rat.instField commGroupWithZero),
--                                     inv_isModeAOp_field (Finding A15: import-context
--                                     effect from Mathlib.Data.Real.Basic via apparatus chain),
--                                     OperationalField.toOperationalGroupUnits (Finding A15:
--                                     import-context effect from GroupWithZero.Units.Basic),
--                                     ℚˣ demonstrations (Stage 5, via bridge),
--                                     ℚ Module instances + demonstrations (v0.4.0 Stage 4)
--
-- ## No sorry, no admit
--
-- v0.2.0 completion: sorryAx ELIMINATED from image_isOperationalAddSubgroup_isModeBOp.
-- The intentional sorry of v0.1.0 (Mode B skeleton) is now a complete proof.
-- v0.3.0 (Stages 1-5): no sorry, no admit in any new object.
-- All 55 public objects (31 v0.1.0 + 15 v0.2.0 + 9 v0.3.0 Stages 1-5) are axiom-clean.
-- v0.3.0 Stage 5 adds 1 named public object (OperationalField.toOperationalGroupUnits)
-- + 5 anonymous examples demonstrating ℚˣ as OperationalGroup.
-- Classical.choice appears in ℚ instances (logical, Finding A14), in
-- inv_isModeAOp_field (import-context, Finding A15), and in
-- OperationalField.toOperationalGroupUnits (proof-structural, Finding A15/A16).
-- v0.4.0 Stages 1-5: no sorry, no admit.
-- v0.4.0 adds 9 new public objects:
--   zsmul_isOperational (Stage 1, axiom profile []).
--   OperationalModule (Stage 3, axiom profile []).
--   instOperationalModuleIntInt, int_smul_isOperational, int_two_smul_three_isOperational
--     (Stage 4, axiom profile [propext]).
--   instOperationalModuleRatRat, rat_smul_isOperational, rat_half_smul_third_isOperational
--     (Stage 4, axiom profile [propext, Classical.choice, Quot.sound]).
--   smul_isModeAOp (Stage 5, axiom profile []).
-- Total public objects: 64 (55 v0.1.0-v0.3.0 + 9 v0.4.0 Stages 1+3+4+5).
-- Stage 2 reconnaissance produced no new public objects (Finding A16 is documentation only).
-- v1.0.0: no new public objects — documentation polish only. v1.0.0 ≅ v0.4.0 mathematically.

import VRCycle.Algebra.AddGroup
import VRCycle.Algebra.Instances
import VRCycle.Algebra.ModeA
import VRCycle.Algebra.Subgroups
import VRCycle.Algebra.ModeBExample
import VRCycle.Algebra.Ring
import VRCycle.Algebra.MulGroup
import VRCycle.Algebra.Field
import VRCycle.Algebra.Module
