-- VRCycle: Algebra.lean
-- Module index for the VR Operational Algebra cycle — v0.3.0 (in progress; v0.2.0 complete).
--
-- ## What this module is
--
-- The eighth work in the VR Cycle: **Operational Algebra**.
--
-- Demonstrates that the VR-Apparatus framework (meta-formalised in v1.0.0,
-- DOI 10.5281/zenodo.20380344) extends naturally to algebraic structures.
-- Specifically: the predicate-wrapping apparatus (PredicateOperationality)
-- applies to additive groups and rings, with subgroups and substantive Mode B audit.
--
-- ## Architecture
--
-- ### v0.1.0 (additive groups — complete, tag v1.8-vr-operational-algebra-v0.1.0)
-- VRCycle/Algebra/AddGroup.lean     — OperationalAddGroup typeclass (v0.1.0 Stage 1)
-- VRCycle/Algebra/Instances.lean    — ℤ and ZMod n instances (v0.1.0 Stages 2, 4)
-- VRCycle/Algebra/ModeA.lean        — Mode A closure theorems + PredicateOperationality (v0.1.0 Stage 3)
-- VRCycle/Algebra/Subgroups.lean    — Operational subgroups (v0.1.0 Stage 5)
-- VRCycle/Algebra/ModeBExample.lean — Mode B skeleton → substantive audit (v0.1.0→v0.2.0)
--
-- ### v0.2.0 (rings — complete, tag v1.9-vr-operational-algebra-v0.2.0)
-- VRCycle/Algebra/Ring.lean         — OperationalRing typeclass + bridge instance (v0.2.0 Stages 1-2)
-- VRCycle/Algebra/Instances.lean    — ℤ and ZMod n as OperationalRing (v0.2.0 Stages 3-4)
-- VRCycle/Algebra/ModeA.lean        — mul_isModeAOp, npow_isOperational (v0.2.0 Stage 5)
-- VRCycle/Algebra/ModeBExample.lean — Substantive Mode B audit, sorryAx eliminated (v0.2.0 Stage 6)
--
-- ### v0.3.0 (fields + multiplicative groups — Stages 1-5 complete)
-- VRCycle/Algebra/MulGroup.lean     — OperationalGroup typeclass, multiplicative (v0.3.0 Stage 1)
-- VRCycle/Algebra/Field.lean        — OperationalField typeclass + bridges (v0.3.0 Stages 2, 5)
-- VRCycle/Algebra/Instances.lean    — ℚ as OperationalField + ℚˣ demos (v0.3.0 Stages 3, 5)
-- VRCycle/Algebra/ModeA.lean        — Mode A theorems for multiplicative groups + field (v0.3.0 Stage 4)
--
-- ## Stage index (v0.1.0)
--
-- Stage 1 (complete): OperationalAddGroup typeclass. Finding A0: multiplicative
--   typeclass removed — no v0.1.0 multiplicative instances (recognition discipline).
-- Stage 2: ℤ instance (Instances.lean, OperationalAddGroup ℤ).
-- Stage 3: Mode A theorems + PredicateOperationality instance (ModeA.lean).
-- Stage 4: ZMod n instance (Instances.lean extension).
-- Stage 5: Operational subgroups (Subgroups.lean).
-- Stage 6: Mode B skeleton example (ModeBExample.lean). Findings A7, A8.
-- Stage 7: Polish, full audit, git. Tag v1.8-vr-operational-algebra-v0.1.0.
--
-- ## Stage index (v0.2.0)
--
-- Stage 1 (complete): OperationalRing typeclass (Ring.lean).
--   extends Ring R with IsOperational + 5 closure axioms (0, +, -, 1, *).
--   Axiom profile: [].
-- Stage 2 (complete): OperationalCommRing OMITTED (Finding A9 — recognition discipline).
--   Bridge instance OperationalRing.toOperationalAddGroup implemented.
--   Axiom profile of bridge: [].
-- Stage 3 (complete): ℤ as OperationalRing (Instances.lean §5-6).
--   instOperationalRingInt; IsOperational := fun _ => True.
--   Finding A10 first observed: ring ceiling = additive-group ceiling = [propext].
-- Stage 4 (complete): ZMod n as OperationalRing (Instances.lean §7-8).
--   instOperationalRingZMod [NeZero n]; IsOperational := fun _ => True.
--   Finding A10 confirmed: ring ceiling = [propext, Quot.sound] (unchanged from additive).
-- Stage 5 (complete): Ring Mode A theorems (ModeA.lean §4-7).
--   instPredOpRing, mul_isModeAOp, npow_isOperational.
--   Recognition discipline: one_isOperational_bridge omitted (is already a typeclass field);
--   mul_chain_isOperational omitted (derivable from compose).
--   Axiom profile: all [].
-- Stage 6 (complete): Substantive Mode B audit (ModeBExample.lean §2).
--   image_isOperationalAddSubgroup_isModeBOp: sorry eliminated.
--   Key step: obtain ⟨x, hxS, rfl⟩ := hy; exact hW x (hS x hxS).
--   Finding A11: algebraic Mode B = one proof step; contrast analytic Mode B (limits, choice).
--   Axiom profile of main theorem: [propext] (down from [propext, sorryAx]).
-- Stage 7 (complete): Polish, full audit, README, git.
--   Tag: v1.9-vr-operational-algebra-v0.2.0.
--
-- ## Public object inventory (complete)
--
-- ### v0.1.0 (31 objects across 5 files)
--
-- AddGroup.lean (1):
--   OperationalAddGroup (class)
--
-- Instances.lean §1-4 (8):
--   instOperationalAddGroupInt        (instance, OperationalAddGroup ℤ)
--   int_isOperational                 (theorem, ∀ n : ℤ, IsOperational n)
--   int_add_isOperational             (theorem, closure under +)
--   int_three_plus_five_isOperational (theorem, concrete demo)
--   instOperationalAddGroupZMod       (instance, OperationalAddGroup (ZMod n))
--   zmod_isOperational                (theorem, ∀ x : ZMod n, IsOperational x)
--   zmod5_add_isOperational           (theorem, concrete closure)
--   zmod5_two_plus_three_isOperational (theorem, concrete demo)
--
-- ModeA.lean §1-3 (5):
--   instPredOpAddGroup    (instance, PredicateOperationality G IsOperational)
--   add_isModeAOp         (theorem, IsModeAOp₂ (+))
--   neg_isModeAOp         (theorem, IsModeAOp (-))
--   sub_isModeAOp         (theorem, IsModeAOp₂ (-))
--   nsmul_isOperational   (theorem, ∀ n : ℕ, IsOperational (n • a))
--
-- Subgroups.lean (8):
--   IsOperationalAddSubgroup          (def, ∀ x ∈ H, IsOperational x)
--   bot_isOperationalAddSubgroup      (theorem, ⊥ is operational)
--   top_isOperationalAddSubgroup      (theorem, ⊤ is operational)
--   inf_isOperationalAddSubgroup      (theorem, ⊓ of operational is operational)
--   OperationalSubgroup               (structure, H : AddSubgroup G, proof : IsOperational...)
--   instInfOperationalSubgroup        (instance, OperationalSubgroup closed under ⊓)
--   instTopOperationalSubgroup        (instance, ⊤ as OperationalSubgroup)
--   instBotOperationalSubgroup        (instance, ⊥ as OperationalSubgroup)
--
-- ModeBExample.lean (9):
--   neg_isModeBOp                              (theorem, Mode B for negation)
--   neg_modeb_lift                             (def, Mode B lift)
--   neg_modeb_lift_val                         (theorem, @[simp])
--   image_isOperationalAddSubgroup_isModeBOp   (theorem, substantive Mode B audit)
--   operationalImage_lift                      (def, Mode B lift)
--   operationalImage_lift_val                  (theorem, @[simp])
--   int_ker_isOperationalAddSubgroup           (theorem, concrete ℤ kernel)
--   int_image_isOperationalAddSubgroup         (theorem, concrete ℤ image)
--   int_to_zmod_ker_isOperationalAddSubgroup   (theorem, concrete ℤ→ZMod kernel)
--
-- ### v0.3.0 (Stages 1-4 complete; 24 new objects across 4 files)
--
-- MulGroup.lean (1):
--   OperationalGroup                       (class, extends Group G)
--
-- Field.lean (3):
--   OperationalField                           (class, extends Field K)
--   OperationalField.toOperationalRing         (instance, bridge OperationalField → OperationalRing)
--   OperationalField.toOperationalGroupUnits   (instance, bridge OperationalField → OperationalGroup Kˣ)
--
-- Instances.lean §9-10 (5):
--   instOperationalFieldRat                (instance, OperationalField ℚ)
--   rat_half_isOperational                 (theorem, IsOperational (1/2 : ℚ))
--   rat_half_plus_third_isOperational      (theorem, closure + demo)
--   rat_product_inv_isOperational          (theorem, closure * and ⁻¹ demo)
--   rat_sub_isOperational                  (theorem, closure - demo)
--
-- ModeA.lean §8-10 (8):
--   MulGroup.instPredOpMulGroup            (instance, PredicateOperationality G IsOperational)
--   MulGroup.mul_isModeAOp                 (theorem, IsModeAOp₂ (*))
--   MulGroup.inv_isModeAOp                 (theorem, IsModeAOp (·⁻¹) for OperationalGroup)
--   MulGroup.div_isModeAOp                 (theorem, IsModeAOp₂ (/))
--   MulGroup.npow_isOperational            (theorem, ∀ n : ℕ, IsOperational (a ^ n))
--   MulGroup.zpow_isOperational            (theorem, ∀ n : ℤ, IsOperational (a ^ n))
--   instPredOpField                        (instance, PredicateOperationality K IsOperational)
--   inv_isModeAOp_field                    (theorem, IsModeAOp (·⁻¹) for OperationalField)
--   [7 examples in §§8-10, not public objects]
--
-- Instances.lean §11 (5 examples, not public objects):
--   [OperationalGroup ℚˣ via bridge]       (example, bridge fires for ℚˣ)
--   [1 : ℚˣ is operational]               (example, unit element)
--   [2ˣ ∈ ℚˣ is operational]              (example, concrete unit via mk0)
--   [2ˣ * 3ˣ is operational]              (example, mul closure in ℚˣ)
--   [(2ˣ)⁻¹ is operational]               (example, inv closure in ℚˣ)
--
-- (ℚˣ examples are anonymous examples, not named public objects;
--  the key deliverable is OperationalField.toOperationalGroupUnits in Field.lean)
--
-- ### v0.2.0 (15 new objects across 3 files; 1 sorry eliminated in ModeBExample.lean)
--
-- Ring.lean (2):
--   OperationalRing                        (class, extends Ring R)
--   OperationalRing.toOperationalAddGroup  (instance, bridge)
--
-- Instances.lean §5-8 (10):
--   instOperationalRingInt              (instance, OperationalRing ℤ)
--   int_one_isOperational               (theorem, IsOperational 1 in ℤ)
--   int_mul_isOperational               (theorem, closure under * in ℤ)
--   int_two_mul_three_isOperational     (theorem, concrete demo)
--   int_sum_mul_isOperational           (theorem, chained + and *)
--   instOperationalRingZMod             (instance, OperationalRing (ZMod n))
--   zmod5_one_isOperational             (theorem, IsOperational 1 in ZMod 5)
--   zmod5_mul_isOperational             (theorem, closure under * in ZMod 5)
--   zmod5_two_mul_three_isOperational   (theorem, concrete demo)
--   zmod7_sum_mul_isOperational         (theorem, chained + and * in ZMod 7)
--
-- ModeA.lean §4-7 (3):
--   instPredOpRing      (instance, PredicateOperationality R IsOperational)
--   mul_isModeAOp       (theorem, IsModeAOp₂ (*))
--   npow_isOperational  (theorem, ∀ n : ℕ, IsOperational (a ^ n))
--
-- ## Findings catalog (v0.1.0 + v0.2.0 + v0.3.0 Stages 1-4)
--
-- ### v0.1.0 Findings (A0–A8)
--
-- A0: Multiplicative typeclass OMITTED — no v0.1.0 instances exist.
--     Recognition discipline: do not abstract preemptively.
--     (Parallel: OperationalCommRing omitted in v0.2.0, Finding A9.)
--
-- A1: Lean 4 `extends` for typeclasses works correctly with mathlib's Ring hierarchy.
--     (First confirmed in v0.1.0 with AddGroup; extended to Ring in v0.2.0.)
--
-- A2: `toAddGroup := inferInstance` resolves the bridge correctly.
--     Lean synthesises the AddGroup instance from AddCommGroup via the ring chain.
--
-- A3: VR-Apparatus framework reuses WITHOUT modification for additive groups.
--     `PredicateOperationality` zero-field marker requires no ring-specific changes.
--     Confirmed in v0.2.0: apparatus reuse extends to full ring structure (instPredOpRing).
--
-- A4: neg_isModeAOp pulls [propext] despite neg being defined algebraically.
--     Lean's Neg elaboration requires propositional extensionality for lambda reductions.
--     Multiplication does NOT pull [propext] (pure algebraic composition).
--     Contrast: mul_isModeAOp is [] in v0.2.0, confirming [] is possible for binary ops.
--
-- A5: Axiom ceiling hierarchy for algebraic structures:
--     [] → [propext] → [propext, Quot.sound] → [propext, Classical.choice, Quot.sound].
--     ℤ objects: [propext]. ZMod n objects: [propext, Quot.sound].
--     Classical.choice ABSENT from all algebraic objects (confirmed v0.1.0 + v0.2.0).
--
-- A6: IsOperationalAddSubgroup as predicate (not typeclass) is the correct design.
--     No inheritance diamond; no elaboration issues. ⊥/⊤/⊓ proved as simple theorems.
--     Omitted: OperationalSubgroup as typeclass (redundant; predicate suffices for v0.1.0).
--
-- A7: Mode B operation on algebraic objects is structurally similar to Mode B on
--     analytic objects (VR-Audit Hahn-Banach), but the algebraic case is simpler:
--     the witness is immediate (subgroup membership), not a choice function.
--
-- A8: Trivial vs substantive Mode B:
--     neg_isModeBOp (trivial): W = True, proof = trivial.
--     image_isOperationalAddSubgroup_isModeBOp (substantive): W = operational-morphism
--     condition, proof extracts constructive witness from mem_map.
--
-- ### v0.2.0 Findings (A9–A11)
--
-- A9: OperationalCommRing OMITTED — recognition discipline applied proactively.
--     Form A (extends CommRing R, OperationalRing R): FAILS — immediate diamond on toRing.
--     Form B (extends CommRing R, all axioms duplicated): COMPILES but no new content.
--     Verdict: [OperationalRing R] [CommRing R] in context suffices; no new typeclass.
--     Direct analogue of Finding A0 for the multiplicative commutative case.
--
-- A10: Ring extension does NOT escalate the axiom ceiling.
--     ℤ: OperationalAddGroup ceiling = OperationalRing ceiling = [propext].
--     ZMod n: OperationalAddGroup ceiling = OperationalRing ceiling = [propext, Quot.sound].
--     Classical.choice ABSENT from all ring objects (including mul, pow, one).
--     Principle: ceiling determined by underlying type's infrastructure, not algebraic depth.
--
-- A11: Algebraic Mode B audit requires ONE PROOF STEP.
--     image_isOperationalAddSubgroup_isModeBOp proof:
--       obtain ⟨x, hxS, rfl⟩ := hy; exact hW x (hS x hxS)
--     Reason: AddSubgroup.mem_map provides CONSTRUCTIVE existential (no Classical.choice).
--     Contrast with analytic Mode B (Hahn-Banach): limit arguments, classical extension,
--     substantial infrastructure. Algebraic Mode B is mechanically extractable from
--     constructive witnesses built into mathlib's algebraic API.
--
-- ### v0.3.0 Findings (A12–A15, Stages 1-4)
--
-- A12: Recognition discipline REVERSAL — OperationalGroup introduced when justified.
--     v0.1.0 Finding A0: multiplicative OperationalGroup omitted (no instances).
--     v0.3.0 Stage 1: multiplicative OperationalGroup INTRODUCED (Fields → Kˣ).
--     v0.3.0 Stage 5: bridge instance OperationalField.toOperationalGroupUnits delivered.
--     The abstraction was revived in Stage 1 because THIS bridge exists; Stage 5 proves it.
--     Bidirectional recognition discipline: remove preemptive abstractions AND
--     introduce justified abstractions when users (instances) arrive.
--     Full circle from A0 (removed) → A12 (anticipated) → Stage 5 (concrete).
--     ℚˣ as OperationalGroup is the natural first instance — Finding A12 CONFIRMED.
--
-- A13: OperationalField currently does not introduce axioms beyond those of Field K.
--     OperationalField class: [propext, Quot.sound] — inherited from Field's RatCast.
--     Bridge OperationalField → OperationalRing: [propext, Quot.sound].
--     This is an empirical observation for the current v0.3.0 build, not a meta-law.
--     The ceiling is determined by Field K's infrastructure (DivisionRing → RatCast),
--     not by the VR operational layer added above it.
--
-- A14: ℚ concrete instances reach full analysis ceiling [propext, Classical.choice, Quot.sound].
--     instOperationalFieldRat and all ℚ demonstration theorems: full ceiling.
--     Root cause: Rat.instField (via commGroupWithZero inverse infrastructure).
--     This is the first time Classical.choice appears in concrete algebraic instances
--     in the VR Cycle (previously absent from all ℤ and ZMod n objects).
--     Principle: ℚ's field structure for inversion requires classical reasoning about
--     the zero case (commGroupWithZero convention: 0⁻¹ = 0 requires choice in the proof).
--
-- A15: Import-context ceiling escalation for inv_isModeAOp_field.
--     inv_isModeAOp_field (generic, [OperationalField K]): [propext, Classical.choice, Quot.sound].
--     instPredOpField (same [OperationalField K], no (·⁻¹) in type): [propext, Quot.sound].
--     Root cause: Apparatus import chain imports Mathlib.Data.Real.Basic (via
--     VRCycle.Apparatus.ModeA → VRCycle.Apparatus.Wrapping → VRCycle.Audit.Computable
--     → Mathlib.Data.Real.Basic). This introduces ℝ instances that affect how Lean
--     resolves Inv K for generic [Field K] when (·⁻¹) appears in the IsModeAOp type.
--     The Classical.choice is an import-context effect, NOT a logical property of
--     inv_isOperational. The logical ceiling remains [propext, Quot.sound].
--     Contrast: MulGroup.inv_isModeAOp (same IsModeAOp + inv structure, [OperationalGroup G]):
--     [propext] — no import escalation because Group doesn't import ℝ-related Mathlib.
--     This finding extends A5: import context can escalate the apparent ceiling
--     beyond what the logic requires.
--
-- ## Axiom profile summary (v0.1.0 + v0.2.0 + v0.3.0 Stages 1-4)
--
--   []                              — OperationalAddGroup, OperationalRing, OperationalGroup
--                                     (v0.3.0 Stage 1), all bridge instances,
--                                     all PredicateOperationality instances except instPredOpField,
--                                     add_/mul_/sub_isModeAOp, nsmul_/npow_isOperational,
--                                     MulGroup.mul_/div_isModeAOp, MulGroup.npow_/zpow_isOp,
--                                     IsOperationalAddSubgroup, ⊥/⊤/⊓ theorems,
--                                     neg_isModeBOp, image_isOperationalAddSubgroup_isModeBOp
--
--   [propext]                       — ℤ AddGroup instances + demonstrations,
--                                     ℤ Ring instances + demonstrations,
--                                     neg_isModeAOp (Neg elaboration, Finding A4),
--                                     MulGroup.inv_isModeAOp (Inv elaboration, A4 mirror),
--                                     Mode B lifts and lift_val,
--                                     int_ker/image_isOperationalAddSubgroup
--
--   [propext, Quot.sound]           — ZMod n AddGroup instances + demonstrations,
--                                     ZMod n Ring instances + demonstrations,
--                                     Subgroups.lean theorems involving ZMod n,
--                                     int_to_zmod_ker_isOperationalAddSubgroup,
--                                     OperationalField (v0.3.0 Stage 2),
--                                     OperationalField.toOperationalRing (bridge),
--                                     instPredOpField
--
--   [propext, Classical.choice, Quot.sound]
--                                   — ℚ instances + demonstrations (v0.3.0 Stage 3,
--                                     Finding A14: Rat.instField commGroupWithZero),
--                                     inv_isModeAOp_field (Finding A15: import-context
--                                     effect from Mathlib.Data.Real.Basic via apparatus chain),
--                                     OperationalField.toOperationalGroupUnits (Finding A15:
--                                     import-context effect from GroupWithZero.Units.Basic),
--                                     ℚˣ demonstrations (Stage 5, via bridge)
--
-- ## No sorry, no admit
--
-- v0.2.0 completion: sorryAx ELIMINATED from image_isOperationalAddSubgroup_isModeBOp.
-- The intentional sorry of v0.1.0 (Mode B skeleton) is now a complete proof.
-- v0.3.0 (Stages 1-4): no sorry, no admit in any new object.
-- All 55 public objects (31 v0.1.0 + 15 v0.2.0 + 9 v0.3.0 Stages 1-5) are axiom-clean.
-- v0.3.0 Stage 5 adds 1 named public object (OperationalField.toOperationalGroupUnits)
-- + 5 anonymous examples demonstrating ℚˣ as OperationalGroup.
-- Classical.choice appears in ℚ instances (logical, Finding A14), in
-- inv_isModeAOp_field (import-context, Finding A15), and in
-- OperationalField.toOperationalGroupUnits (import-context, Finding A15 pattern).

import VRCycle.Algebra.AddGroup
import VRCycle.Algebra.Instances
import VRCycle.Algebra.ModeA
import VRCycle.Algebra.Subgroups
import VRCycle.Algebra.ModeBExample
import VRCycle.Algebra.Ring
import VRCycle.Algebra.MulGroup
import VRCycle.Algebra.Field
