-- VRCycle/Topology/FreeFrame.lean
-- VR-Topology v1.0.0 — Stage 1: Free frame on a type of generators.
--
-- Builds `FreeFrame G : Type u` as a quotient of `FreeFramePre G` by the frame
-- congruence relation, proves the `Order.Frame` instance, and establishes the
-- universal property (`lift` / `lift_gen` / `lift_unique`).
--
-- No operational predicates. No VR-Apparatus dependencies. Pure mathlib
-- infrastructure (cf. `FreeMagma`, `FreeMonoid`, `FreeGroup`, `FreeAbelianGroup`).
--
-- Design notes (Stage 1, with PLAN_1.md):
--
-- * sSup-input representation (Finding T1).  The `Set (FreeFramePre G) → FreeFramePre G`
--   form (PLAN's variant γ) is rejected by Lean's positivity checker because
--   `Set α = α → Prop` puts `α` in negative position.  We use variant (δ):
--   `sSupι : ∀ (ι : Type u), (ι → FreeFramePre G) → FreeFramePre G` — an
--   indexed-family constructor.  Strictly positive (codomain of `→` is positive),
--   yields a useful recursor (recursive hypothesis available per index), and
--   the factor-level `sSup : Set (FreeFrame G) → FreeFrame G` is built
--   constructively via `Subtype` of the preimage through `Quot.mk` — no
--   `Quot.out`, no `Classical.choice`.
--
-- * Finding T2.  The frame congruence relation `FreeFrameEquiv` is extended
--   with two axioms — `le_sSupι_index` and `sSupι_le_of_le` — characterising
--   `sSupι` as a supremum.  Without them, `CompleteLattice` cannot close;
--   they are the minimal completion of the axiom set required to make
--   `sSupι` a true supremum operator (not just an abstract symbol).

import Mathlib.Order.CompleteBooleanAlgebra
import Mathlib.Order.Hom.CompleteLattice

namespace VRCycle.Topology

universe u

-- ============================================================
-- Section 1: Pre-quotient inductive type
-- ============================================================

/-- Pre-quotient free frame expressions over a type of generators `G`.
Each constructor mirrors one operation of the frame signature.
`sSupι` accepts an indexed family `ι → FreeFramePre G` in the same universe
as `G`; this is variant (δ) from the stage-1 design notes — strictly
positive, recursor-friendly, and avoids the positivity rejection that
variant (γ) (`Set`-direct) would have triggered. -/
inductive FreeFramePre (G : Type u) : Type u where
  | gen   : G → FreeFramePre G
  | bot   : FreeFramePre G
  | top   : FreeFramePre G
  | inf   : FreeFramePre G → FreeFramePre G → FreeFramePre G
  | sup   : FreeFramePre G → FreeFramePre G → FreeFramePre G
  | sSupι : ∀ (ι : Type u), (ι → FreeFramePre G) → FreeFramePre G

-- ============================================================
-- Section 2: Frame congruence relation
-- ============================================================

/-- The frame congruence relation on `FreeFramePre G`.
Generated by equivalence (refl/symm/trans), congruence under each constructor,
finite lattice axioms, identities, infinite distributivity, and (Finding T2)
the characterisation of `sSupι` as a supremum. -/
inductive FreeFrameEquiv (G : Type u) : FreeFramePre G → FreeFramePre G → Prop where
  -- Equivalence structure
  | refl  : ∀ a, FreeFrameEquiv G a a
  | symm  : ∀ a b, FreeFrameEquiv G a b → FreeFrameEquiv G b a
  | trans : ∀ a b c,
      FreeFrameEquiv G a b → FreeFrameEquiv G b c → FreeFrameEquiv G a c
  -- Congruence under constructors
  | inf_congr : ∀ a₁ a₂ b₁ b₂,
      FreeFrameEquiv G a₁ a₂ → FreeFrameEquiv G b₁ b₂ →
      FreeFrameEquiv G (.inf a₁ b₁) (.inf a₂ b₂)
  | sup_congr : ∀ a₁ a₂ b₁ b₂,
      FreeFrameEquiv G a₁ a₂ → FreeFrameEquiv G b₁ b₂ →
      FreeFrameEquiv G (.sup a₁ b₁) (.sup a₂ b₂)
  /-- `sSupι` is congruent under index-set "bisimulation": if every index of
  one family has an equivalent target in the other, the sSupι's are equivalent. -/
  | sSupι_congr : ∀ {ι κ : Type u} (f : ι → FreeFramePre G) (g : κ → FreeFramePre G),
      (∀ i, ∃ j, FreeFrameEquiv G (f i) (g j)) →
      (∀ j, ∃ i, FreeFrameEquiv G (f i) (g j)) →
      FreeFrameEquiv G (.sSupι ι f) (.sSupι κ g)
  -- Lattice axioms — meet
  | inf_comm  : ∀ a b, FreeFrameEquiv G (.inf a b) (.inf b a)
  | inf_assoc : ∀ a b c,
      FreeFrameEquiv G (.inf (.inf a b) c) (.inf a (.inf b c))
  | inf_idem  : ∀ a, FreeFrameEquiv G (.inf a a) a
  -- Lattice axioms — join
  | sup_comm  : ∀ a b, FreeFrameEquiv G (.sup a b) (.sup b a)
  | sup_assoc : ∀ a b c,
      FreeFrameEquiv G (.sup (.sup a b) c) (.sup a (.sup b c))
  | sup_idem  : ∀ a, FreeFrameEquiv G (.sup a a) a
  -- Absorption
  | sup_inf_self : ∀ a b, FreeFrameEquiv G (.sup a (.inf a b)) a
  | inf_sup_self : ∀ a b, FreeFrameEquiv G (.inf a (.sup a b)) a
  -- Boundedness
  | inf_top : ∀ a, FreeFrameEquiv G (.inf a .top) a
  | sup_bot : ∀ a, FreeFrameEquiv G (.sup a .bot) a
  | inf_bot : ∀ a, FreeFrameEquiv G (.inf a .bot) .bot
  | sup_top : ∀ a, FreeFrameEquiv G (.sup a .top) .top
  -- Compatibility between binary sup and indexed sSupι (via PUnit ⊕ PUnit)
  | sup_sSupι_pair : ∀ a b,
      FreeFrameEquiv G (.sup a b)
        (.sSupι (PUnit.{u+1} ⊕ PUnit.{u+1}) (Sum.elim (fun _ => a) (fun _ => b)))
  -- The KEY frame axiom — infinite distributivity (over indexed family)
  | inf_sSupι_distrib : ∀ a (ι : Type u) (f : ι → FreeFramePre G),
      FreeFrameEquiv G (.inf a (.sSupι ι f)) (.sSupι ι (fun i => .inf a (f i)))
  -- Finding T2: sSupι as supremum (least upper bound)
  | le_sSupι_index : ∀ {ι : Type u} (f : ι → FreeFramePre G) (i : ι),
      FreeFrameEquiv G (.inf (f i) (.sSupι ι f)) (f i)
  | sSupι_le_of_le : ∀ {ι : Type u} (f : ι → FreeFramePre G) (a : FreeFramePre G),
      (∀ i, FreeFrameEquiv G (.inf (f i) a) (f i)) →
      FreeFrameEquiv G (.inf (.sSupι ι f) a) (.sSupι ι f)

-- ============================================================
-- Section 3: Quotient and constructor functions
-- ============================================================

/-- The free frame on generators `G`: formal frame expressions modulo
the frame congruence relation. -/
def FreeFrame (G : Type u) : Type u := Quot (FreeFrameEquiv G)

namespace FreeFrame

variable {G : Type u}

/-- Embed a generator. -/
def gen (g : G) : FreeFrame G := Quot.mk _ (.gen g)

/-- Bottom element. -/
def bot : FreeFrame G := Quot.mk _ .bot

/-- Top element. -/
def top : FreeFrame G := Quot.mk _ .top

/-- Binary meet. -/
def inf : FreeFrame G → FreeFrame G → FreeFrame G :=
  Quot.lift₂
    (fun a b => Quot.mk (FreeFrameEquiv G) (.inf a b))
    (fun _ _ _ h => Quot.sound (.inf_congr _ _ _ _ (.refl _) h))
    (fun _ _ _ h => Quot.sound (.inf_congr _ _ _ _ h (.refl _)))

/-- Binary join. -/
def sup : FreeFrame G → FreeFrame G → FreeFrame G :=
  Quot.lift₂
    (fun a b => Quot.mk (FreeFrameEquiv G) (.sup a b))
    (fun _ _ _ h => Quot.sound (.sup_congr _ _ _ _ (.refl _) h))
    (fun _ _ _ h => Quot.sound (.sup_congr _ _ _ _ h (.refl _)))

/-- Set-indexed supremum.  Defined constructively via the `Subtype` of the
preimage of `s` through `Quot.mk`; this avoids `Quot.out` and therefore
`Classical.choice` (Finding T1). -/
def sSup (s : Set (FreeFrame G)) : FreeFrame G :=
  Quot.mk _ (.sSupι { a : FreeFramePre G // Quot.mk _ a ∈ s } Subtype.val)

-- ============================================================
-- Section 4: Helpers — Quot.mk-form of constructors
-- ============================================================

@[simp] theorem inf_mk (a b : FreeFramePre G) :
    inf (Quot.mk (FreeFrameEquiv G) a) (Quot.mk (FreeFrameEquiv G) b) =
    Quot.mk (FreeFrameEquiv G) (.inf a b) := rfl

@[simp] theorem sup_mk (a b : FreeFramePre G) :
    sup (Quot.mk (FreeFrameEquiv G) a) (Quot.mk (FreeFrameEquiv G) b) =
    Quot.mk (FreeFrameEquiv G) (.sup a b) := rfl

theorem sSup_def (s : Set (FreeFrame G)) :
    sSup s = Quot.mk (FreeFrameEquiv G)
      (.sSupι { a // Quot.mk _ a ∈ s } Subtype.val) := rfl

/-- Recover a `FreeFrameEquiv` witness from a `Quot` equality.
Uses `Quot.exact` + induction over `EqvGen`. -/
private theorem equiv_of_quot_eq {a b : FreeFramePre G}
    (h : Quot.mk (FreeFrameEquiv G) a = Quot.mk _ b) : FreeFrameEquiv G a b := by
  have hg := Quot.exact _ h
  induction hg with
  | rel _ _ r => exact r
  | refl a => exact .refl a
  | symm _ _ _ ih => exact .symm _ _ ih
  | trans _ _ _ _ _ ih₁ ih₂ => exact .trans _ _ _ ih₁ ih₂

-- ============================================================
-- Section 5: Order — LE/LT
-- ============================================================

instance : LE (FreeFrame G) where
  le a b := inf a b = a

instance : LT (FreeFrame G) where
  lt a b := a ≤ b ∧ ¬ b ≤ a

theorem le_def (a b : FreeFrame G) : a ≤ b ↔ inf a b = a := Iff.rfl

theorem le_mk_iff (a b : FreeFramePre G) :
    (Quot.mk (FreeFrameEquiv G) a : FreeFrame G) ≤ Quot.mk _ b
      ↔ FreeFrameEquiv G (.inf a b) a := by
  refine ⟨fun h => equiv_of_quot_eq h, fun h => ?_⟩
  show Quot.mk _ (.inf a b) = Quot.mk _ a
  exact Quot.sound h

-- ============================================================
-- Section 6: Lattice helper lemmas
-- ============================================================

private theorem inf_comm_eq (a b : FreeFrame G) : inf a b = inf b a := by
  induction a using Quot.ind with | _ a =>
  induction b using Quot.ind with | _ b =>
  simp only [inf_mk]
  exact Quot.sound (.inf_comm _ _)

private theorem inf_assoc_eq (a b c : FreeFrame G) :
    inf (inf a b) c = inf a (inf b c) := by
  induction a using Quot.ind with | _ a =>
  induction b using Quot.ind with | _ b =>
  induction c using Quot.ind with | _ c =>
  simp only [inf_mk]
  exact Quot.sound (.inf_assoc _ _ _)

private theorem inf_idem_eq (a : FreeFrame G) : inf a a = a := by
  induction a using Quot.ind with | _ a =>
  simp only [inf_mk]
  exact Quot.sound (.inf_idem _)

private theorem sup_comm_eq (a b : FreeFrame G) : sup a b = sup b a := by
  induction a using Quot.ind with | _ a =>
  induction b using Quot.ind with | _ b =>
  simp only [sup_mk]
  exact Quot.sound (.sup_comm _ _)

private theorem sup_assoc_eq (a b c : FreeFrame G) :
    sup (sup a b) c = sup a (sup b c) := by
  induction a using Quot.ind with | _ a =>
  induction b using Quot.ind with | _ b =>
  induction c using Quot.ind with | _ c =>
  simp only [sup_mk]
  exact Quot.sound (.sup_assoc _ _ _)

private theorem sup_idem_eq (a : FreeFrame G) : sup a a = a := by
  induction a using Quot.ind with | _ a =>
  simp only [sup_mk]
  exact Quot.sound (.sup_idem _)

private theorem sup_inf_self_eq (a b : FreeFrame G) : sup a (inf a b) = a := by
  induction a using Quot.ind with | _ a =>
  induction b using Quot.ind with | _ b =>
  simp only [inf_mk, sup_mk]
  exact Quot.sound (.sup_inf_self _ _)

private theorem inf_sup_self_eq (a b : FreeFrame G) : inf a (sup a b) = a := by
  induction a using Quot.ind with | _ a =>
  induction b using Quot.ind with | _ b =>
  simp only [inf_mk, sup_mk]
  exact Quot.sound (.inf_sup_self _ _)

private theorem inf_top_eq (a : FreeFrame G) : inf a top = a := by
  induction a using Quot.ind with | _ a =>
  show Quot.mk _ (.inf a .top) = Quot.mk _ a
  exact Quot.sound (.inf_top _)

private theorem sup_bot_eq (a : FreeFrame G) : sup a bot = a := by
  induction a using Quot.ind with | _ a =>
  show Quot.mk _ (.sup a .bot) = Quot.mk _ a
  exact Quot.sound (.sup_bot _)

private theorem inf_bot_eq (a : FreeFrame G) : inf a bot = bot := by
  induction a using Quot.ind with | _ a =>
  show Quot.mk _ (.inf a .bot) = Quot.mk _ .bot
  exact Quot.sound (.inf_bot _)

private theorem sup_top_eq (a : FreeFrame G) : sup a top = top := by
  induction a using Quot.ind with | _ a =>
  show Quot.mk _ (.sup a .top) = Quot.mk _ .top
  exact Quot.sound (.sup_top _)

-- ============================================================
-- Section 7: Partial order
-- ============================================================

private theorem le_refl_eq (a : FreeFrame G) : a ≤ a := inf_idem_eq a

private theorem le_trans_eq {a b c : FreeFrame G}
    (hab : a ≤ b) (hbc : b ≤ c) : a ≤ c := by
  show inf a c = a
  calc inf a c
      = inf (inf a b) c := by rw [hab]
    _ = inf a (inf b c) := inf_assoc_eq a b c
    _ = inf a b := by rw [hbc]
    _ = a := hab

private theorem le_antisymm_eq {a b : FreeFrame G}
    (hab : a ≤ b) (hba : b ≤ a) : a = b := by
  calc a = inf a b := hab.symm
       _ = inf b a := inf_comm_eq a b
       _ = b := hba

instance : PartialOrder (FreeFrame G) where
  le := (· ≤ ·)
  lt := (· < ·)
  le_refl := le_refl_eq
  le_trans _ _ _ := le_trans_eq
  le_antisymm _ _ := le_antisymm_eq

private theorem inf_le_left_eq (a b : FreeFrame G) : inf a b ≤ a := by
  show inf (inf a b) a = inf a b
  calc inf (inf a b) a
      = inf (inf b a) a := by rw [inf_comm_eq a b]
    _ = inf b (inf a a) := inf_assoc_eq b a a
    _ = inf b a := by rw [inf_idem_eq]
    _ = inf a b := inf_comm_eq b a

private theorem inf_le_right_eq (a b : FreeFrame G) : inf a b ≤ b := by
  show inf (inf a b) b = inf a b
  calc inf (inf a b) b
      = inf a (inf b b) := inf_assoc_eq a b b
    _ = inf a b := by rw [inf_idem_eq]

private theorem le_inf_eq {a b c : FreeFrame G}
    (hab : a ≤ b) (hac : a ≤ c) : a ≤ inf b c := by
  show inf a (inf b c) = a
  calc inf a (inf b c)
      = inf (inf a b) c := (inf_assoc_eq a b c).symm
    _ = inf a c := by rw [hab]
    _ = a := hac

private theorem le_sup_left_eq (a b : FreeFrame G) : a ≤ sup a b := by
  show inf a (sup a b) = a
  exact inf_sup_self_eq a b

private theorem le_sup_right_eq (a b : FreeFrame G) : b ≤ sup a b := by
  show inf b (sup a b) = b
  calc inf b (sup a b)
      = inf b (sup b a) := by rw [sup_comm_eq a b]
    _ = b := inf_sup_self_eq b a

private theorem le_top_eq (a : FreeFrame G) : a ≤ top := by
  show inf a top = a; exact inf_top_eq a

private theorem bot_le_eq (a : FreeFrame G) : bot ≤ a := by
  show inf bot a = bot
  rw [inf_comm_eq]; exact inf_bot_eq a

-- ============================================================
-- Section 8: sSup properties — le_sSup, sSup_le
-- ============================================================

private theorem le_sSup_eq {s : Set (FreeFrame G)} {a : FreeFrame G}
    (ha : a ∈ s) : a ≤ sSup s := by
  induction a using Quot.ind with | _ pa =>
  -- a = Quot.mk pa, ⟨pa, ha⟩ ∈ Subtype (Quot.mk _ · ∈ s)
  show inf (Quot.mk _ pa) (sSup s) = Quot.mk _ pa
  rw [sSup_def]
  show Quot.mk _ (.inf pa (.sSupι _ Subtype.val)) = Quot.mk _ pa
  exact Quot.sound (.le_sSupι_index Subtype.val ⟨pa, ha⟩)

private theorem sSup_le_eq {s : Set (FreeFrame G)} {a : FreeFrame G}
    (h : ∀ b ∈ s, b ≤ a) : sSup s ≤ a := by
  induction a using Quot.ind with | _ pa =>
  show inf (sSup s) (Quot.mk _ pa) = sSup s
  rw [sSup_def]
  show Quot.mk _ (.inf (.sSupι _ Subtype.val) pa) = Quot.mk _ (.sSupι _ Subtype.val)
  apply Quot.sound
  apply FreeFrameEquiv.sSupι_le_of_le
  rintro ⟨x, hx⟩
  -- hx : Quot.mk x ∈ s
  have hle : (Quot.mk (FreeFrameEquiv G) x : FreeFrame G) ≤ Quot.mk _ pa := h _ hx
  exact equiv_of_quot_eq hle

-- ============================================================
-- Section 9: SupSet / InfSet / CompleteLattice
-- ============================================================

instance : Top (FreeFrame G) := ⟨top⟩
instance : Bot (FreeFrame G) := ⟨bot⟩
instance : Min (FreeFrame G) := ⟨inf⟩
instance : Max (FreeFrame G) := ⟨sup⟩
instance : SupSet (FreeFrame G) := ⟨sSup⟩

/-- `sInf` defined as the join of all lower bounds (standard Galois trick).
With this, `CompleteSemilatticeInf` follows from `CompleteSemilatticeSup`. -/
def sInf (s : Set (FreeFrame G)) : FreeFrame G :=
  sSup {a | ∀ b ∈ s, a ≤ b}

instance : InfSet (FreeFrame G) := ⟨sInf⟩

private theorem sInf_le_eq {s : Set (FreeFrame G)} {a : FreeFrame G}
    (ha : a ∈ s) : sInf s ≤ a := by
  apply sSup_le_eq
  intro b hb
  exact hb a ha

private theorem le_sInf_eq {s : Set (FreeFrame G)} {a : FreeFrame G}
    (h : ∀ b ∈ s, a ≤ b) : a ≤ sInf s :=
  le_sSup_eq h

/-- The frame congruence `.inf c (.sup a b) ≡ .sup (.inf c a) (.inf c b)`
on `FreeFramePre`.  Derived from `inf_sSupι_distrib` + `sup_sSupι_pair`. -/
private theorem inf_sup_distrib_pre (a b c : FreeFramePre G) :
    FreeFrameEquiv G (.inf c (.sup a b)) (.sup (.inf c a) (.inf c b)) := by
  -- .inf c (.sup a b)
  -- ≡ .inf c (.sSupι (PUnit ⊕ PUnit) (Sum.elim (·=a) (·=b)))   [sup_sSupι_pair]
  -- ≡ .sSupι _ (fun i => .inf c (Sum.elim (·=a) (·=b) i))      [inf_sSupι_distrib]
  -- ≡ .sup (.inf c a) (.inf c b)                              [sup_sSupι_pair, reversed]
  refine .trans _ _ _ (.inf_congr _ _ _ _ (.refl _) (.sup_sSupι_pair _ _)) ?_
  refine .trans _ _ _ (.inf_sSupι_distrib _ _ _) ?_
  refine .symm _ _ ?_
  refine .trans _ _ _ (.sup_sSupι_pair _ _) ?_
  -- Now both sides are .sSupι (PUnit ⊕ PUnit) <of two slightly different things>
  apply FreeFrameEquiv.sSupι_congr
  · rintro (⟨⟩ | ⟨⟩) <;> simp <;> exact ⟨_, .refl _⟩
  · rintro (⟨⟩ | ⟨⟩) <;> simp <;> exact ⟨_, .refl _⟩

instance instCompleteLattice : CompleteLattice (FreeFrame G) where
  inf := inf
  sup := sup
  inf_le_left := inf_le_left_eq
  inf_le_right := inf_le_right_eq
  le_inf _ _ _ := le_inf_eq
  le_sup_left := le_sup_left_eq
  le_sup_right := le_sup_right_eq
  sup_le := by
    intro a b c hac hbc
    induction a using Quot.ind with | _ pa =>
    induction b using Quot.ind with | _ pb =>
    induction c using Quot.ind with | _ pc =>
    show Quot.mk _ (.inf (.sup pa pb) pc) = Quot.mk _ (.sup pa pb)
    have eac : FreeFrameEquiv G (.inf pa pc) pa := equiv_of_quot_eq hac
    have ebc : FreeFrameEquiv G (.inf pb pc) pb := equiv_of_quot_eq hbc
    apply Quot.sound
    -- .inf (.sup pa pb) pc ≡ .inf pc (.sup pa pb)            [comm]
    --                      ≡ .sup (.inf pc pa) (.inf pc pb) [distrib_pre]
    --                      ≡ .sup pa pb                     [comm + eac/ebc]
    refine .trans _ _ _ (.inf_comm _ _) ?_
    refine .trans _ _ _ (inf_sup_distrib_pre _ _ _) ?_
    refine .sup_congr _ _ _ _ ?_ ?_
    · exact .trans _ _ _ (.inf_comm _ _) eac
    · exact .trans _ _ _ (.inf_comm _ _) ebc
  le_refl := le_refl_eq
  le_trans _ _ _ := le_trans_eq
  le_antisymm _ _ := le_antisymm_eq
  top := top
  bot := bot
  le_top := le_top_eq
  bot_le := bot_le_eq
  sSup := sSup
  le_sSup _ _ ha := le_sSup_eq ha
  sSup_le _ _ h := sSup_le_eq h
  sInf := sInf
  sInf_le _ _ ha := sInf_le_eq ha
  le_sInf _ _ h := le_sInf_eq h

-- ============================================================
-- Section 10: Order.Frame instance via ofMinimalAxioms
-- ============================================================

/-- Infinite distributivity inequality required by `Order.Frame.MinimalAxioms`.
We prove `≤`; the reverse `≥` is provided automatically by mathlib. -/
private theorem inf_sSup_le_iSup_inf_eq (a : FreeFrame G) (s : Set (FreeFrame G)) :
    a ⊓ sSup s ≤ ⨆ b ∈ s, a ⊓ b := by
  induction a using Quot.ind with | _ pa =>
  -- Step 1: rewrite a ⊓ sSup s as a sSup over an image set.
  have hLHS : (Quot.mk _ pa : FreeFrame G) ⊓ sSup s =
      sSup ((fun b : FreeFrame G => Quot.mk (FreeFrameEquiv G) pa ⊓ b) '' s) := by
    show inf _ (sSup s) = sSup _
    rw [sSup_def, sSup_def]
    show Quot.mk _ (.inf pa (.sSupι _ Subtype.val)) = Quot.mk _ (.sSupι _ Subtype.val)
    apply Quot.sound
    -- .inf pa (.sSupι ι Subtype.val) ≡ .sSupι ι (fun i => .inf pa (Subtype.val i))
    refine .trans _ _ _ (.inf_sSupι_distrib _ _ _) ?_
    -- Now bisimulate this with .sSupι ι' Subtype.val where ι' is the preimage on the RHS set.
    apply FreeFrameEquiv.sSupι_congr
    · intro ⟨q, hq⟩
      -- q ∈ preimage s, so Quot.mk q ∈ s; map q ↦ inf pa q
      refine ⟨⟨.inf pa q, ?_⟩, .refl _⟩
      -- Show: Quot.mk (.inf pa q) ∈ (image (Quot.mk pa ⊓ ·)) s
      refine ⟨Quot.mk _ q, hq, ?_⟩
      show (Quot.mk _ pa : FreeFrame G) ⊓ Quot.mk _ q = Quot.mk _ (.inf pa q)
      rfl
    · intro ⟨y, hy⟩
      -- y is in preimage of (image (Quot.mk pa ⊓ ·)) s
      -- so Quot.mk y = Quot.mk pa ⊓ b for some b ∈ s
      rcases hy with ⟨b, hb, hbq⟩
      induction b using Quot.ind with | _ pb =>
      -- hbq : Quot.mk pa ⊓ Quot.mk pb = Quot.mk y, i.e. Quot.mk (.inf pa pb) = Quot.mk y
      refine ⟨⟨pb, hb⟩, ?_⟩
      -- Want: FreeFrameEquiv (.inf pa (Subtype.val ⟨pb, hb⟩)) y
      -- i.e. FreeFrameEquiv (.inf pa pb) y
      exact equiv_of_quot_eq hbq
  rw [hLHS]
  apply sSup_le_eq
  rintro x ⟨b, hb, rfl⟩
  -- x = Quot.mk pa ⊓ b, b ∈ s.  Want: Quot.mk pa ⊓ b ≤ ⨆ b' ∈ s, Quot.mk pa ⊓ b'
  exact le_biSup _ hb

/-- `FreeFrame G` is a frame. -/
instance instFrame : Order.Frame (FreeFrame G) := Order.Frame.ofMinimalAxioms
  { __ := instCompleteLattice
    inf_sSup_le_iSup_inf := inf_sSup_le_iSup_inf_eq }

-- ============================================================
-- Section 11: Universal property — lift, lift_gen, lift_unique
-- ============================================================

section Lift

variable {M : Type*} [Order.Frame M]

/-- Recursive interpretation of a `FreeFramePre G` expression in any frame `M`,
given a function `f : G → M` on generators.  Direct structural recursion
(the `sSupι` constructor has an indexed family of recursive sub-terms). -/
def liftPre (f : G → M) : FreeFramePre G → M
  | .gen g => f g
  | .bot => ⊥
  | .top => ⊤
  | .inf a b => liftPre f a ⊓ liftPre f b
  | .sup a b => liftPre f a ⊔ liftPre f b
  | .sSupι ι g => ⨆ i : ι, liftPre f (g i)

/-- `liftPre` respects the frame congruence relation. -/
private theorem liftPre_sound (f : G → M) {a b : FreeFramePre G}
    (h : FreeFrameEquiv G a b) : liftPre f a = liftPre f b := by
  induction h with
  | refl _ => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | inf_congr _ _ _ _ _ _ ih₁ ih₂ =>
      simp only [liftPre]; rw [ih₁, ih₂]
  | sup_congr _ _ _ _ _ _ ih₁ ih₂ =>
      simp only [liftPre]; rw [ih₁, ih₂]
  | sSupι_congr _ _ _ _ ih₁ ih₂ =>
      simp only [liftPre]
      -- Two sSup's over different index sets; show equal by mutual ≤
      apply le_antisymm
      · apply iSup_le
        intro i
        rcases ih₁ i with ⟨j, hij⟩
        -- need: liftPre f (f_lhs i) ≤ ⨆ j, liftPre f (f_rhs j)
        -- Wait, we don't have ih's on the inner equivalences.
        sorry
      · sorry
  | inf_comm _ _ => simp only [liftPre]; exact inf_comm _ _
  | inf_assoc _ _ _ => simp only [liftPre]; exact inf_assoc _ _ _
  | inf_idem _ => simp only [liftPre]; exact inf_idem _
  | sup_comm _ _ => simp only [liftPre]; exact sup_comm _ _
  | sup_assoc _ _ _ => simp only [liftPre]; exact sup_assoc _ _ _
  | sup_idem _ => simp only [liftPre]; exact sup_idem _
  | sup_inf_self _ _ => simp only [liftPre]; exact sup_inf_self
  | inf_sup_self _ _ => simp only [liftPre]; exact inf_sup_self
  | inf_top _ => simp only [liftPre]; exact inf_top _
  | sup_bot _ => simp only [liftPre]; exact sup_bot _
  | inf_bot _ => simp only [liftPre]; exact inf_bot _
  | sup_top _ => simp only [liftPre]; exact sup_top _
  | sup_sSupι_pair _ _ =>
      simp only [liftPre]
      sorry
  | inf_sSupι_distrib _ _ _ =>
      simp only [liftPre]; exact inf_iSup_eq _ _
  | le_sSupι_index _ _ => sorry
  | sSupι_le_of_le _ _ _ ih => sorry

/-- Lift of `f : G → M` to a frame homomorphism `FreeFrame G → M`. -/
def lift (f : G → M) : FrameHom (FreeFrame G) M where
  toFun := Quot.lift (liftPre f) (liftPre_sound f)
  map_inf' := by
    intro a b
    induction a using Quot.ind with | _ a =>
    induction b using Quot.ind with | _ b =>
    rfl
  map_top' := rfl
  map_sSup' := by
    intro s
    show Quot.lift (liftPre f) _ (sSup s) = sSup _
    rw [sSup_def]
    show liftPre f (.sSupι _ Subtype.val) = sSup _
    simp only [liftPre]
    -- ⨆ i : Subtype _, liftPre f i.val = sSup (Quot.lift ... '' s)
    sorry

theorem lift_gen (f : G → M) (g : G) : lift f (gen g) = f g := rfl

theorem lift_unique (f : G → M) (h : FrameHom (FreeFrame G) M)
    (hgen : ∀ g, h (gen g) = f g) : h = lift f := by
  sorry

end Lift

end FreeFrame

end VRCycle.Topology
